actual testを追加

diff --git a/.github/workflows/smoke-ctf.yml b/.github/workflows/smoke-ctf.yml
--- a/.github/workflows/smoke-ctf.yml
+++ b/.github/workflows/smoke-ctf.yml
@@ -9,8 +9,6 @@ on:
     paths:
       - src/ctf/**
       - .github/workflows/smoke-ctf.yaml
-      # - .github/actions/**
-      # - build/**
 
 env:
   image: ctf
@@ -30,9 +28,9 @@ jobs:
       run: |
         IMAGE="${{ env.image }}"
         
+        export DOCKER_BUILDKIT=1
         set -e
 
-        export DOCKER_BUILDKIT=1
         echo "(*) Installing @devcontainer/cli"
         npm install -g @devcontainers/cli
 
@@ -49,10 +47,13 @@ jobs:
         export DOCKER_BUILDKIT=1
         set -e
 
+        # Run actual test
         echo "(*) Running test..."
         id_label="test-container=${IMAGE}"
+        devcontainer exec --workspace-folder $(pwd)/src/$IMAGE --id-label ${id_label} /bin/sh -c 'set -e && if [ -f "test-project/test.sh" ]; then cd test-project && if [ "$(id -u)" = "0" ]; then chmod +x test.sh; else sudo chmod +x test.sh; fi && ./test.sh; else ls -a; fi'
 
         echo "(*) Docker image details..."
         docker images
 
+        # Clean up
         docker rm -f $(docker container ls -f "label=${id_label}" -q)
